### ISSUE TITLE
Cornercase inside `\text`

### ISSUE THREAD

**Issue by alani1** [Khan/translation-assistant#2]
I have seen in one in commit e6d8a657dfa9bec92921571d7186a5015bc4f2cd you mentioned this cornercase inside a `\text` command. What we have done with our translation tools is that we simply have a dictionary for strings which are automatically replaced. This helps alot, however I guess to make it language independent and editable by users would be quite challenging.

https://github.com/ulikoehler/KATranslationTools

**Comment by danielhollas** [comment]
@mpolyak I think this issue can be closed, `\\text{}` command is supported for some time now. 

btw: Thanks for merging #8!

**Comment by mpolyak** [comment]
👍
