### ISSUE TITLE
Translation of math syntax for different locales

### ISSUE THREAD

**Issue by danielhollas** [Khan/translation-assistant#5]
It would be wonderful if ST could translate math notations for different locales. The most obvious and probably most useful example is converting decimal points to decimal commas. The list of math notations in different locales is maintained in this [google doc](https://docs.google.com/spreadsheets/d/1qgi-KjumcZ6yru19U5weqZK9TosRlTdLZqbXbABBJoQ/edit#gid=0) and some of them should not be hard to implement.

Actually, it seems that such a functionality is already there in function [translateMath](https://github.com/Khan/translation-assistant/blob/9a93ade02e4aa10f2a7087257d075de4c429db2b/src/translation-assistant.js#L347) 
For Portuguese it translates sinus operator \sin to sen. This should be trivially extendable to other cases. In my local branch, I tested that it works for decimal commas. If KA is OK with this I'll create a pull request. 

There seems to be one important caveat. In the current implementation, the math notation in the original string that is used to make the templates cannot be translated. For example, if I translate decimal point to a decimal comma, ST will not offer translations. So the workflow would have to be:

1. Translate the string but keep original math notation. 
2. Use ST, which will automatically use correct notation.
3. Fix the notation in the original string.

I did not look deep enough to see how difficult it would be to fix this. But even this workflow would be immensely helpful for translators IMHO.

Note that this would partly cover this [Asana task](https://app.asana.com/0/422384364449217/292172389849229)

**Comment by danielhollas** [comment]
Maybe something like this?

https://gist.github.com/danielhollas/50da17131767d9168a1cc4174b7daa9f

**Comment by danielhollas** [comment]
So it seems that the original functionality was broken. I think I have a working version (without the caveat) which converts decimal points to commas and \mult to \cdot for selected locales based on the spreadsheet referenced above. 

We would still need to decide on the default behavior of ST. What if the original translated string that is used to generate template, does not contain expected translation? e.g. translator forgets to replace decimal point for decimal comma. We have few options.

1. Treat it as a mistake, but suggest translations anyway with the "correct" translation.
2. Treat it as a mistake and do not offer any translations. This could alert the translator that something is wrong.
3. Treat it as a deliberate action, perhaps it was some edge case. We should then offer translations that are consistent with the translated string.

Option 3 would be quite a bit harder to implement.

**Comment by kevinbarabash** [comment]
I would like to eventually see a separation of locale from language.  Right now I feel like we're assuming certain locations from the language.  There are a couple of situations were we don't want to do this:
- the same language is used in multiple locales, but each locale has a different format, e.g. English is used in US and Canada, but the US uses a comma for thousands separator whereas Canada uses a space.
- users living in a particular country but speak a different language from the official language

I think the first case if probably more common than the second, but both can be solved by localizing numbers independent of translations.

Also, my understand is that webapp is already doing this localization when content is being served.  @davidflanagan is that correct?

**Comment by davidflanagan** [comment]
I've got no idea what we do when we serve math content. And to be honest, I didn't even know this repo existed... (I've worked on translation analytics and LTTs, but have not actually worked on translations themselves). Maybe @xymostech can answer this question?

**Comment by xymostech** [comment]
Agreed with @kevinbarabash that making the smart translations try to handle this is probably not the right way.

We do have code that automatically replaces "." with "{,}" (and "{,}" with ".") for numbers in math expressions. Sometimes, when strings only have numbers and some symbols in them, we will automatically try to do this transformation. Unfortunately, we the number of strings that we currently end up applying this transformation to is very small 😞 (I couldn't find a string that we do this for looking through statistics for about 15 minutes, for reference).

Also, we recently reduced the scope of strings that can be auto-translated, because one locale needs to move around the `%` and `$` signs around numbers, so things like `1.5%` are now not getting auto-converted either.

Putting that auto-conversion into KaTeX is the wrong choice, it's just supposed to be a math renderer, not opinionated about the input. That said, we could probably add a layer on top of KaTeX that does this conversion before we try to render each expression using KaTeX. That wouldn't be too hard. We'd have to figure out all of the replacements on the frontend though, which we don't currently have. The python babel library does this for us on the backend, maybe there's a javascript equivalent.

We could also make the code that does the "." to "{,}" replacement better by letting it work on strings that are more than just numbers and symbols. This is probably a good option, but we have to be careful parsing LaTeX on the server (as usual).

**Comment by danielhollas** [comment]
Thank you all for comments. Very interesting. Couple general remarks from me:

1. I'd never suggested that this is THE right way to do this. However, it seems to me that the proper way of solving this is hard and not a priority AFAIK so I'd suggest that this is still worth doing because
  - the functionality is already there and I have the PR almost ready, so it should not take that much extra time
  - it would probably save quite a lot of time for the translators. As per @xymostech comments, it seems we still need to manually translate almost all decimal numbers and the same goes for \mutl -> \cdot conversion. I can tell you that it is not a fun job. For these frequent cases, the ST is simply unusable at this point.

2. btw: The KaTex idea is strange for the decimal point conversion, but IMHO is perfectly reasonable for things like \mult to \cdot; it would be simply equivalent to latex's \renewcommand. Is this implemented in KaTeX?

Since we are having this conversation...I've just recently made an Asana ticket for untranslatable decimal numbers. 
https://app.asana.com/0/253524899192327/540366868647302
Now I am not sure whether that ticket is valid if there really is some magic going on behind the scenes. @xymostech would you please have a look at that when you have a chance? 

@kevinbarabash Definitely agree on locale versus language issue. As you may know, there is a Local Curriculum project starting at KA and solving this is one of the top priorities (at least according to the language advocates Working Group). But again, the timeline is quite uncertain at this point.

**Comment by mpolyak** [comment]
Thanks for linking to the Asana ticket @danielhollas!

As per the ticket we should have more specific information about how, when, and for which type of content numbers are automatically localized.

My sense, and to echo others, is that if we already do automatic localization in other parts of the system, also adding similar functionality here, to the Translation Assistant, may not be the best approach.

Hopefully with the additional information after Thursday we can identify concrete enhancement that can be made to the system (e.g. Translation Dashboard) and log them as issues in JIRA.

**Comment by danielhollas** [comment]
@xymostech I am visiting KAHQ tomorrow, so I thought it might be a good idea to talk about this in person. It seems to me that the conversation here got way broader than was my intention. See you soon!

**Comment by danielhollas** [comment]
The functionality is largely implemented by #8 and #10. There is room for improvement (more regexes), but I'll close this issue for now.
