### ISSUE TITLE
Translation suggestion looks incorrect

### ISSUE THREAD

**Issue by mpolyak** [Khan/translation-assistant#9]
Testing strings taken from:

https://www.khanacademy.org/translations/edit/cs/e/multiplying-and-dividing-by-10/by-pattern
https://crowdin.com/translate/khanacademy/26574/enus-cs#3314816

```
    it('does not offer translation, but it should?', function() {
        const allItems = [{
            englishStr: 'The answers:\n\n$50 \\div 10=5$\n\n$50 \\times 10=500$',
            translatedStr: 'The answers:\n\n$50 \\div 10=5$\n\n$50 \\times 10=500$',
        }];
        const itemsToTranslate = [{
            englishStr: 'The answers:\n\n$460 \\div 10=46$\n\n$460 \\times 10=4600$',
            translatedStr: '',
        }];
        const translatedStrs = [null]; // This shouldn't be `null`?

        assertSuggestions(allItems, itemsToTranslate, translatedStrs);
    });
```
For the first test case I was expecting a translation to be offered.

```
    it('offers translation but the output looks wrong!', function() {
        const allItems = [{
            englishStr: '$50 \\div 10=5$',
            translatedStr: '$50 \\div 10=5$',
        }];
        const itemsToTranslate = [{
            englishStr: '$460 \\div 10=46$',
            translatedStr: '',
        }];
        const translatedStrs = ['$4{,}0 \\mathbin{:} 10{,}46$']; // This doesn't look correct!

        assertSuggestions(allItems, itemsToTranslate, translatedStrs);
    });
```

The second test case is concerning, as the output incorrectly formats `460` and `10=46`.

@danielhollas can you please take a look at this? Should we revert the changes for now?

**Comment by danielhollas** [comment]
The first case looks ok to me, it should not offer translation, because default lang is cs and you did not translate the \\div.

The second case, oh my, that's bad. It is possible that I did not escape the dot so it takes any characters between two numbers and changes that to comma. Let's please revert for now.

"Luckily", I don't think this will affect users. I did a bit of debugging in TP, looking into maticore.js, and it seems that the locale (variable lang) is not properly passed to Translation Assistant, I am getting null.

Is Manticore code open source so I can have a look? I should probably file a separate JIRA issue for this.

**Comment by mpolyak** [comment]
> The first case looks ok to me, it should not offer translation, because default lang is cs and you did not translate the \div.

Translating `\div` to `\mathbin{:}` still returns `null`:

```
    it('does not offer translation, but it should?', function() {
        const allItems = [{
            englishStr: 'The answers:\n\n$50 \\div 10=5$\n\n$50 \\times 10=500$',
            translatedStr: 'The answers:\n\n$50 \\mathbin{:} 10=5$\n\n$50 \\times 10=500$',
        }];
        const itemsToTranslate = [{
            englishStr: 'The answers:\n\n$460 \\div 10=46$\n\n$460 \\times 10=4600$',
            translatedStr: '',
        }];
        const translatedStrs = [null]; // This shouldn't be `null`?

        assertSuggestions(allItems, itemsToTranslate, translatedStrs);
    });
```

I don't see translations for this pattern of string in https://www.khanacademy.org/translations/edit/cs/e/multiplying-and-dividing-by-10/by-pattern, so if it's expected to return `null` then the behaviour is as expected?

> "Luckily", I don't think this will affect users. I did a bit of debugging in TP, looking into maticore.js, and it seems that the locale (variable lang) is not properly passed to Translation Assistant, I am getting null.

Thanks, I'll debug to see what's going on.

> Is Manticore code open source so I can have a look? I should probably file a separate JIRA issue for this.

Manticore is part of the core product code base and is not open source.

**Comment by mpolyak** [comment]
>  I did a bit of debugging in TP, looking into maticore.js, and it seems that the locale (variable lang) is not properly passed to Translation Assistant, I am getting null.

Definitely looks like a bug that's been there for at least a year. It's only passing `null` into TranslationAssistant when progress and status of items is changed. I think it's unrelated to this specific issue of not getting suggestion for this example string.

**Comment by danielhollas** [comment]
Perfect. Note that I noticed that sometimes it passes `en`, sometimes `null`, but never `cs`.

I have a fix (embararring) for this issue #9. Will create PR shortly...

**Comment by mpolyak** [comment]
> Perfect. Note that I noticed that sometimes it passes `en`.

Hmm, ok there might be two bugs here then. I would expect to always be `null` and initially always `cs` when the editor is first loaded.

Can you please list the actions you took (navigation, clicking, etc) in the editor so I can try and reproduce this?

**Comment by danielhollas** [comment]
> Hmm, ok there might be two bugs here then. I would expect to always be null 
Actually no, it shoul be `en` when it creates templates from original English strings and 'cs' afterwords.
(at least this is what I see in the test suite). Will look into it...

**Comment by danielhollas** [comment]
@mpolyak sorry for a potential confusion from my comments above. I was printing `lang` from within the translateMath function, and in that case it indeed printed 'en', as it should since it is called with hard-coded 'en' locale when templates are created.

When I print lang in the TranslationAssistant constructor, I get only null.

Should I file a separate JIRA ticket for this bug will you handle it still as part of this?

**Comment by mpolyak** [comment]
@danielhollas, no worries. I'll handle it as part of integrating the regex fix. I'll correct the bug in manticore that passes `null` instead of the specified translation editor page locale as part of the deploy.

**Comment by mpolyak** [comment]
Fix is deployed.
